import { redirect } from "next/navigation";
import { createServerClient } from "@/lib/supabase/server";
import { format } from "date-fns";

export default async function BookingsPage() {
  const supabase = createServerClient();
  const {
    data: { session }
  } = await supabase.auth.getSession();

  if (!session) {
    redirect("/");
  }

  const { data: bookings } = await supabase
    .from("bookings")
    .select("id, scheduled_at, meeting_link, status, lead:leads(first_name, last_name, email, phone)")
    .eq("broker_id", session.user.id)
    .order("scheduled_at", { ascending: true });

  return (
    <main className="mx-auto w-full max-w-5xl space-y-6">
      <header>
        <h1 className="text-3xl font-semibold text-white">Consultations</h1>
        <p className="text-sm text-white/60">Review upcoming and past bookings generated by Riftly.</p>
      </header>

      <section className="rounded-2xl border border-white/10 bg-white/5 p-6 shadow-lg">
        <div className="grid grid-cols-1 gap-4">
          {(bookings ?? []).map((booking) => (
            <article
              key={booking.id}
              className="flex flex-col justify-between gap-3 rounded-xl border border-white/10 bg-slate-950/50 p-4 sm:flex-row sm:items-center"
            >
              <div>
                <p className="text-sm font-semibold text-white">
                  {booking.lead?.first_name} {booking.lead?.last_name}
                </p>
                <p className="text-xs text-white/50">{booking.lead?.email ?? "No email"}</p>
              </div>
              <div className="text-sm text-white/70">
                {format(new Date(booking.scheduled_at), "EEE, MMM d • HH:mm")}
              </div>
              <div className="text-xs uppercase tracking-wide text-white/50">{booking.status}</div>
              <div>
                {booking.meeting_link ? (
                  <a
                    href={booking.meeting_link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm font-medium text-brand-200 hover:text-brand-100"
                  >
                    View meeting
                  </a>
                ) : (
                  <span className="text-xs text-white/40">No link yet</span>
                )}
              </div>
            </article>
          ))}

          {(bookings?.length ?? 0) === 0 ? (
            <div className="rounded-xl border border-dashed border-white/15 p-10 text-center text-white/60">
              No consultations scheduled yet. Bookings will appear once Riftly qualifies a lead and finds a slot.
            </div>
          ) : null}
        </div>
      </section>
    </main>
  );
}
